# Generated by Django 2.2.2 on 2019-07-16 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20190716_0236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='payment_tipe',
            new_name='payment_type',
        ),
    ]
