# Generated by Django 2.2.2 on 2019-07-13 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
    ]
