# Generated by Django 2.2.2 on 2019-07-13 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_employee_active'),
    ]

    operations = [
    ]
