# Generated by Django 2.2.2 on 2019-07-13 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20190713_0323'),
    ]

    operations = [
    ]
