# Generated by Django 2.2.2 on 2019-07-13 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0007_auto_20190713_0358'),
    ]

    operations = [
    ]
