# Generated by Django 2.2.2 on 2019-07-13 09:08

from django.db import migrations
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_auto_20190713_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='contract_date_start',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
