# Generated by Django 2.2.2 on 2019-07-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_remove_employee_contracted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='contract_date_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='fired_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
