# Generated by Django 2.2.2 on 2019-07-16 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_auto_20190713_0413'),
    ]

    operations = [
    ]
