# Generated by Django 2.2.2 on 2019-07-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_auto_20190713_0413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='payment_tipe',
        ),
        migrations.AddField(
            model_name='employee',
            name='payment_type',
            field=models.CharField(choices=[('hora', 'Hora'), ('dia', 'Dia'), ('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('mensual', 'Mensual'), ('bimestral', 'Bimestral'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], default='Quincenal', max_length=100),
        ),
    ]
