# Generated by Django 2.2.2 on 2019-07-17 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_auto_20190716_0236'),
        ('employee', '0016_auto_20190716_2140'),
    ]

    operations = [
    ]
