# Generated by Django 2.2.2 on 2019-08-07 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_merge_20190717_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='zip_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
