# Generated by Django 2.2.2 on 2020-03-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0020_auto_20191028_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('sales', 'Ventas'), ('internal', 'Interno')], max_length=20),
        ),
    ]
