# Generated by Django 2.2.2 on 2020-03-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potential_employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='potentialemployee',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
