# Generated by Django 2.2.2 on 2020-01-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
